//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yar.Enterprise.HR.Modal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnterpriseDbEntities : DbContext
    {
        public EnterpriseDbEntities()
            : base("name=EnterpriseDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HR_EMP_PostInformation> HR_EMP_PostInformation { get; set; }
        public virtual DbSet<HR_ORG_Organization> HR_ORG_Organization { get; set; }
        public virtual DbSet<HR_ORG_Position> HR_ORG_Position { get; set; }
        public virtual DbSet<HR_ORG_PositionRoleList> HR_ORG_PositionRoleList { get; set; }
        public virtual DbSet<SYS_Audittrail> SYS_Audittrail { get; set; }
        public virtual DbSet<SYS_RequestMaster> SYS_RequestMaster { get; set; }
        public virtual DbSet<SYS_RequestType> SYS_RequestType { get; set; }
        public virtual DbSet<SYS_Role> SYS_Role { get; set; }
        public virtual DbSet<HR_EMP_OfficeArea> HR_EMP_OfficeArea { get; set; }
        public virtual DbSet<HR_EMP_SalaryLevel> HR_EMP_SalaryLevel { get; set; }
        public virtual DbSet<HR_ORG_Job> HR_ORG_Job { get; set; }
        public virtual DbSet<HR_ORG_JobLevel> HR_ORG_JobLevel { get; set; }
        public virtual DbSet<HR_EMP_Address> HR_EMP_Address { get; set; }
        public virtual DbSet<HR_EMP_BankCard> HR_EMP_BankCard { get; set; }
        public virtual DbSet<HR_EMP_Education> HR_EMP_Education { get; set; }
        public virtual DbSet<HR_EMP_EmployeeContract> HR_EMP_EmployeeContract { get; set; }
        public virtual DbSet<HR_EMP_EmployeeFamily> HR_EMP_EmployeeFamily { get; set; }
        public virtual DbSet<HR_EMP_WorkHistory> HR_EMP_WorkHistory { get; set; }
        public virtual DbSet<HR_EMP_Employee> HR_EMP_Employee { get; set; }
        public virtual DbSet<SYS_COM_BankBranch> SYS_COM_BankBranch { get; set; }
        public virtual DbSet<HR_EMP_OtherContact> HR_EMP_OtherContact { get; set; }
        public virtual DbSet<HR_ORG_LegalEntity> HR_ORG_LegalEntity { get; set; }
        public virtual DbSet<SYS_User> SYS_User { get; set; }
    }
}
