//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yar.Enterprise.HR.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_EMP_Employee
    {
        public System.Guid EmployeeID { get; set; }
        public string EmployeeNumber { get; set; }
        public string EmployeeNameCN { get; set; }
        public string EmployeeNameEN { get; set; }
        public string Gender { get; set; }
        public string IDType { get; set; }
        public string IDNumber { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<System.DateTime> FirstWorkedDate { get; set; }
        public string Nationality { get; set; }
        public Nullable<System.Guid> OfficeAreaID { get; set; }
        public string HukouAddress { get; set; }
        public Nullable<System.DateTime> OnboardDate { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public string TerminationTypeName { get; set; }
        public string EmployeeEMail { get; set; }
        public string EmpStatus { get; set; }
        public string EmployeeStatus { get; set; }
        public Nullable<System.Guid> OrganizationID { get; set; }
        public string OrganizationCode { get; set; }
        public string OrganizationName { get; set; }
        public Nullable<System.Guid> MainJobPositionID { get; set; }
        public string MainJobPostionName { get; set; }
        public string CurrentJobLevelName { get; set; }
        public Nullable<decimal> CurrentJobLevelValue { get; set; }
        public string ExtCode { get; set; }
        public string TeleCode { get; set; }
        public string PersonalEmail { get; set; }
        public string Education { get; set; }
        public string PersonalCellPhone { get; set; }
        public string CPFAccount { get; set; }
        public string EmergencyCellPhone { get; set; }
        public Nullable<System.DateTime> FileTransferInDate { get; set; }
        public Nullable<System.DateTime> FileTransferOutDate { get; set; }
        public string PoliticalStatus { get; set; }
        public string TAG { get; set; }
        public string Description { get; set; }
        public string UserName { get; set; }
        public string MLAccount { get; set; }
        public Nullable<System.DateTime> TrialBeginDate { get; set; }
        public Nullable<System.DateTime> TrialEndDate { get; set; }
        public Nullable<System.Guid> PhotoAttachmentID { get; set; }
        public string Ethnic { get; set; }
        public string ProfessionalTitle { get; set; }
        public string SupplHousingAccount { get; set; }
        public Nullable<int> CostCenterMode { get; set; }
        public string CostCenterCode { get; set; }
        public string ADAccount { get; set; }
        public string ADPassword { get; set; }
        public string ZYPolicyNo { get; set; }
        public Nullable<System.DateTime> PartyJoinInDate { get; set; }
        public string NCUserCode { get; set; }
        public string EmployeeType { get; set; }
        public Nullable<bool> NoTrial { get; set; }
        public string SalaryLevelType { get; set; }
        public Nullable<System.Guid> SalaryLevelID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CreateUserID { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.Guid> UpdateUserID { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid LegalEntityID { get; set; }
        public System.Guid TenantID { get; set; }
    }
}
