//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yar.Enterprise.HR.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_EMP_OfficeArea
    {
        public System.Guid AreaID { get; set; }
        public string AreaCode { get; set; }
        public string AreaName { get; set; }
        public System.DateTime StartTime { get; set; }
        public bool IsUse { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string OtherAddress { get; set; }
        public string DetailAddress { get; set; }
        public string ZipCode { get; set; }
        public string Memo { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CreateUserID { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.Guid> UpdateUserID { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid LegalEntityID { get; set; }
        public System.Guid TenantID { get; set; }
        public decimal AreaSize { get; set; }
    }
}
