//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yar.Enterprise.HR.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_EMP_EmployeeFamily
    {
        public System.Guid FamilyMemberID { get; set; }
        public System.Guid EmployeeID { get; set; }
        public string Name { get; set; }
        public string Relationships { get; set; }
        public string IDType { get; set; }
        public string IDNumber { get; set; }
        public string ContactCellphone { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Job { get; set; }
        public string Company { get; set; }
        public string InsuranceNumber { get; set; }
        public string InsuranceStatus { get; set; }
        public Nullable<System.DateTime> InsuranceStartDate { get; set; }
        public Nullable<System.DateTime> InsuranceEndDate { get; set; }
        public bool IsEmergency { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CreateUserID { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.Guid> UpdateUserID { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid LegalEntityID { get; set; }
        public System.Guid TenantID { get; set; }
    }
}
