//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yar.Enterprise.HR.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_EMP_EmployeeContract
    {
        public System.Guid EmployeeContractID { get; set; }
        public System.Guid EmployeeID { get; set; }
        public string SignMode { get; set; }
        public Nullable<System.Guid> SignApplicationID { get; set; }
        public Nullable<System.Guid> OriginalContractID { get; set; }
        public string ContractType { get; set; }
        public string EmployeeContractNumber { get; set; }
        public System.DateTime EmployeeContractBeginDate { get; set; }
        public Nullable<System.DateTime> EmployeeContractEndDate { get; set; }
        public Nullable<System.DateTime> TrialBeginDate { get; set; }
        public Nullable<System.DateTime> TrialEndDate { get; set; }
        public Nullable<System.Guid> AttachmentID { get; set; }
        public Nullable<System.DateTime> SignDate { get; set; }
        public Nullable<int> SignedTimes { get; set; }
        public string Description { get; set; }
        public bool IsUnfixedTerm { get; set; }
        public bool IsAutoExpandDate { get; set; }
        public bool HaveTrialDate { get; set; }
        public Nullable<System.DateTime> ExpandDate { get; set; }
        public Nullable<System.DateTime> ContractEndDateWarnDate { get; set; }
        public Nullable<System.DateTime> TrialEndDateWarnDate { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CreateUserID { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.Guid> UpdateUserID { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid LegalEntityID { get; set; }
        public System.Guid TenantID { get; set; }
    }
}
