//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yar.Enterprise.HR.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_EMP_Education
    {
        public System.Guid EducationID { get; set; }
        public System.Guid EmployeeID { get; set; }
        public string School { get; set; }
        public string Speciality { get; set; }
        public string EduBG { get; set; }
        public string EduDegree { get; set; }
        public string EduDegreeNumber { get; set; }
        public Nullable<System.DateTime> EduBeginDate { get; set; }
        public Nullable<System.DateTime> EduEndDate { get; set; }
        public bool IsHighestDiploma { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CreateUserID { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.Guid> UpdateUserID { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid LegalEntityID { get; set; }
        public System.Guid TenantID { get; set; }
    }
}
