//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yar.Enterprise.HR.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_ORG_Position
    {
        public System.Guid PositionID { get; set; }
        public string PositionCode { get; set; }
        public string PositionName { get; set; }
        public bool IsFunctionPosition { get; set; }
        public Nullable<System.Guid> ReportToPositionID { get; set; }
        public string PositionCodePath { get; set; }
        public int Headcount { get; set; }
        public bool IsAppraisal { get; set; }
        public bool IsHead { get; set; }
        public bool IsPrincipal { get; set; }
        public bool IsApprover { get; set; }
        public bool IsApplier { get; set; }
        public string PositionDescription { get; set; }
        public System.Guid OrganizationID { get; set; }
        public Nullable<System.Guid> JobID { get; set; }
        public Nullable<System.Guid> PositionLevelID { get; set; }
        public bool IsUse { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CreateUserID { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.Guid> UpdateUserID { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid LegalEntityID { get; set; }
        public System.Guid TenantID { get; set; }
    }
}
