//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yar.Enterprise.HR.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_ORG_LegalEntity
    {
        public System.Guid LegalEntityID { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public string LegalEntityName { get; set; }
        public string LegalEntityCode { get; set; }
        public string EnterpriseType { get; set; }
        public string LegalRepresentativeName { get; set; }
        public string UnifiedCreditRecord { get; set; }
        public Nullable<System.DateTime> BizBeginDate { get; set; }
        public Nullable<System.DateTime> BizEndDate { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string BusinessAddress { get; set; }
        public string PostNumber { get; set; }
        public string TelNumber { get; set; }
        public string FaxNumber { get; set; }
        public string Website { get; set; }
        public string BizScope { get; set; }
        public string Description { get; set; }
        public string AccountBookNumber { get; set; }
        public string LegalCodePath { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CreateUserID { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.Guid> UpdateUserID { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid TenantID { get; set; }
    }
}
