//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yar.Enterprise.HR.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_ORG_Organization
    {
        public System.Guid OrganizationID { get; set; }
        public string OrganizationName { get; set; }
        public string OrganizationCode { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public string CodePath { get; set; }
        public int Sequence { get; set; }
        public string OrganizationType { get; set; }
        public Nullable<System.Guid> HeadPositionID { get; set; }
        public string Description { get; set; }
        public bool IsEnableHeadCountPeriod { get; set; }
        public bool IsIndependentAccounting { get; set; }
        public string AccountBookNumber { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CreateUserID { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.Guid> UpdateUserID { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid LegalEntityID { get; set; }
        public System.Guid TenantID { get; set; }
        public bool IsDisabled { get; set; }
        public string CostCenterCode { get; set; }
    }
}
