//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yar.Enterprise.HR.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_User
    {
        public long Id { get; set; }
        public System.Guid UserId { get; set; }
        public string ResId { get; set; }
        public string Name { get; set; }
        public string LoginName { get; set; }
        public string LoginId { get; set; }
        public string Password { get; set; }
        public string Code { get; set; }
        public string InitPassword { get; set; }
        public string RoleList { get; set; }
        public string UserRoleList { get; set; }
        public int ResState { get; set; }
        public string OrgId { get; set; }
        public string PositionId { get; set; }
        public string BelongOrg { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string UserStatus { get; set; }
        public string UserLevel { get; set; }
        public string UserNo { get; set; }
        public string UserPhotoId { get; set; }
        public string UserType { get; set; }
        public string DataSource { get; set; }
        public string Text1 { get; set; }
        public string Text2 { get; set; }
        public string Text3 { get; set; }
        public string Text4 { get; set; }
        public string Text5 { get; set; }
        public string Text6 { get; set; }
        public string Text7 { get; set; }
        public string Text8 { get; set; }
        public Nullable<System.Guid> LegalId { get; set; }
        public System.Guid TenantId { get; set; }
        public string DataOwner { get; set; }
        public string DataScope { get; set; }
        public string Creator { get; set; }
        public string Updator { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
